### ISSUE TITLE
Buscar e testar bibliotecas de gráficos para utilizar na tela de análise

### ISSUE THREAD

**Issue by RenissonSilva** [RenissonSilva/improov#6]
Testar bibliotecas de gráficos e definir qual será a melhor opção para o nosso projeto

- [x] Pesquisar bibliotecas
- [x] Fazer um pequeno projeto ou branch testando ela

**Comment by lilialnas** [comment]
Ótimo!

**Comment by RenissonSilva** [comment]
Teste com o [chart.js](https://www.chartjs.org/)
![image](https://user-images.githubusercontent.com/40182898/120118903-392f6180-c16b-11eb-8049-2eb79b8b16d0.png)

Branch testando a implementação e criação dos gráficos -  [feature/testing-chart-js](https://github.com/RenissonSilva/improov/commit/17bbf5e9a91ab6af2e69cf5f1d245c2578cf3f4f)
