### ISSUE TITLE
Estudo de fake API

### ISSUE THREAD

**Issue by RenissonSilva** [RenissonSilva/improov#7]
Por conta do limite de requisições que a API do github tem, Ranieri sugeriu utilizar uma fake API para guardar a resposta das chamadas e tratar a partir delas, diminuindo assim a quantidade de requisições que precisaremos fazer.
Verificar como ela opera e fazer o planejamento para modificar como as interações com o github estão funcionando.

[json-server](https://github.com/typicode/json-server)

**Comment by lilialnas** [comment]
Ótimo!

**Comment by EricksonFerreira** [comment]
A API foi estudada e chegamos a conclusão de que não iremos utiliza-la, pois os recursos que ela tem são muito similares aos recursos que o Laravel nos disponibiliza. Por conta disso e da nossa familiaridade com o Laravel resolvemos utiliza-lo para diminuir a quantidade de requisições que precisaremos fazer no site.

**Comment by lilialnas** [comment]
Tá certo!
