### ISSUE TITLE
Visualizar meu dados de análise de desempenho

### ISSUE THREAD

**Issue by EricksonFerreira** [RenissonSilva/improov#8]
Eu **como** usuário **quero** uma tela que mostre dados sobre o meu desempenho **para** acompanhar como está o meu desenvolvimento

- [x] Criar blade da tela
- [x] Importar navbar e footer padrão
- [x] Criar gráfico de ..... (à definir, depende do que vamos fazer no protótipo)

**Comment by RenissonSilva** [comment]
https://github.com/RenissonSilva/improov/commit/f3fb26ce43e1d6216ac48474a0d184bf1f83f235

**Comment by RenissonSilva** [comment]
![image](https://user-images.githubusercontent.com/40182898/123502932-2c951080-d626-11eb-8b73-4d38eb79bf23.png)

**Comment by RenissonSilva** [comment]
Já está funcional e no heroku - [https://improov.herokuapp.com/](https://improov.herokuapp.com/)
